Update lp interop Dockerfile. Remove install of oc. Framework will in…
sclorg/ansible-tests pull request #57
Opened 2024-01-09 12:20 UTC by smatula

…ject correct version of oc

2024-01-11 08:16 UTC, phracek requested changes
The change looks good, but tests are not passing. After 2 days. Can you please review it again what's going on?

2024-01-12 15:10 UTC, smatula commented
[test]

2024-01-15 14:54 UTC, phracek commented
[test]

2024-01-16 11:45 UTC, smatula commented
/ok-to-test

2024-01-16 12:00 UTC, phracek commented
/ok-to-test

2024-01-16 12:01 UTC, smatula commented
/test dotnet-ocp4.15-lp-interop-images dotnet-ocp4.14-lp-interop-images

2024-01-16 14:07 UTC, merged